apiVersion: batch/v1
kind: Job
metadata:
  name: ${JOB_NAME}
  namespace: ${KUBE_NAMESPACE}
  annotations:
    creator: "${KUBE_USERNAME}"
spec:
  ttlSecondsAfterFinished: ${TTL_SECONDS_AFTER_FINISHED}
  backoffLimit: 0
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        creator: "${KUBE_USERNAME}"
    spec:
      nodeSelector:
          mlx.navercorp.com/zone: ${MLXP_ZONE}
      restartPolicy: Never
      terminationGracePeriodSeconds: 60
      containers:
        - name: build
          image: python:3.13
          imagePullPolicy: Always
          workingDir: /workspace
          resources:
            requests:
              memory: "16Gi"
              cpu: "${CPU_REQUEST}"
              nvidia.com/gpu: "${GPU_REQUEST}"
            limits:
              memory: "16Gi"
              cpu: "${CPU_REQUEST}"
              nvidia.com/gpu: "${GPU_REQUEST}"
          command: ["bash", "-euc"]
          args:
            - |
              apt-get update
              apt-get install -y --no-install-recommends ca-certificates git
              git init .
              git remote add origin "${GIT_REPOSITORY}"
              git fetch --depth 1 origin "${GIT_SHA}"
              git checkout --detach FETCH_HEAD

              pip install .[doc]
              export GPYTORCHQR_N_EPOCHS=1
              jupyter nbconvert --to notebook --execute --inplace examples/*.ipynb
              jupyter nbconvert --to notebook --execute --inplace examples/**/*.ipynb
